export const mockProjects = [
  {
    id: "1",
    title: "🌳 Reforestation & Biodiversity Restoration",
    description:
      "A regenerative lending platform on XRPL that funds reforestation and biodiversity projects. Stake RLUSD, earn yield, and track real-world impact through on-chain verifications",
    author: "John Doe",
    category: "Biodiversity",
    daysAgo: 5,
    fundingGoal: 10000,
    currentFunding: 7500,
    fundingPercentage: 75,
    votes: 120,
  },
  {
    id: "2",
    title: "🧑‍⚕️ Humanitarian Health Financing",
    description:
      "A decentralized credit system supporting NGOs in health emergencies. Loans issued in iDebt, milestone-based repayments, and transparent DAO oversight ensure measurable ESG outcomes.",
    author: "Sarah Johnson",
    category: "Health",
    daysAgo: 10,
    fundingGoal: 8000,
    currentFunding: 2000,
    fundingPercentage: 25,
    votes: 45,
  },
  {
    id: "3",
    title: "☀️ Clean Energy Deployment",
    description:
      "An impact-first lending protocol enabling solar and wind infrastructure financing in underserved areas. Stakeholders earn rewards while reducing global carbon footprint.",
    author: "Michael Chen",
    category: "Energy",
    daysAgo: 3,
    fundingGoal: 15000,
    currentFunding: 15000,
    fundingPercentage: 100,
    votes: 200,
  },
  {
    id: "4",
    title: "💧 Clean Water Access Infrastructure",
    description:
      "Finance water purification and delivery systems for communities in need. XiDebt combines real-world infrastructure funding with on-chain transparency and social returns",
    author: "Emily Rodriguez",
    category: "Gaming",
    daysAgo: 8,
    fundingGoal: 12000,
    currentFunding: 6000,
    fundingPercentage: 50,
    votes: 80,
  },
  {
    id: "5",
    title: "🌾 Sustainable Agriculture Credit",
    description:
      "Support small-scale farmers and eco-agriculture cooperatives with long-term loans on XRPL. Stakers back resilient food systems and receive ESG data-backed returns.",
    author: "David Kim",
    category: "Farming",
    daysAgo: 15,
    fundingGoal: 9000,
    currentFunding: 3600,
    fundingPercentage: 40,
    votes: 65,
  },
  {
    id: "6",
    title: "🧑‍🏫 Digital Education for All",
    description:
      "A decentralized financing platform for edtech startups creating access to education in emerging markets. RLUSD staking fuels inclusion, with transparent quarterly repayments.",
    author: "Lisa Wang",
    category: "Education",
    daysAgo: 6,
    fundingGoal: 5000,
    currentFunding: 4000,
    fundingPercentage: 80,
    votes: 95,
  },
]

